export type TProducts = {
    id: number,
    name: string,
    value: number,
    discountPrice: number | null,
    installments: number | null,
    category: string,
    img: string
}

export const products: TProducts[] = [
    {
        id: 1,
        name: "Lustre suspenso rústico",
        value: 1500,
        discountPrice: 33.33,
        installments: 3,
        category: "Lustres",
        img: "../assets/Rectangle 30.png",
    },
    {
        id: 2,
        name: "Lâmpada",
        value: 60,
        discountPrice: 33.3,
        installments: 2,
        category: "Lâmpadas",
        img: "../assets/Rectangle 30 (1).png",
    },
    {
        id: 3,
        name: "Extensão",
        value: 25,
        discountPrice: 32,
        installments: null,
        category: "Acessórios",
        img: "../assets/Rectangle 30 (2).png",
    },
    {
        id: 4,
        name: "Kit de ferramentas",
        value: 100,
        discountPrice: 20,
        installments: 2,
        category: "Ferramentas",
        img: "../assets/Rectangle 30 (3).png",
    },
    {
        id: 5,
        name: "Garfos de mesa inox",
        value: 15,
        discountPrice: 46.6,
        installments: null,
        category: "Utensílios domésticos",
        img: "../assets/Rectangle 30 (4).png",
    },
    {
        id: 6,
        name: "Chuveiro",
        value: 120,
        discountPrice: 16.6,
        installments: 4,
        category: "Acessórios",
        img: "../assets/Rectangle 30 (5).png",
    },
    {
        id: 7,
        name: "Ventilador 2 em 1, mesa e parede",
        value: 50,
        discountPrice: 40,
        installments: null,
        category: "Utensílios domésticos",
        img: "../assets/Rectangle 30 (6).png",
    },
    {
        id: 8,
        name: "Tomada",
        value: 20,
        discountPrice: 50,
        installments: null,
        category: "Acessórios",
        img: "../assets/Rectangle 30 (7).png",
    },
]